### ISSUE TITLE
Add category list

### ISSUE THREAD

**Issue by CullenSharp** [CullenSharp/redux-store#1]
## As a user, I expect to see a list of available product categories in the store so that I can easily browse products

Create a categories component that displays a list of available product categories. Selecting one should fire a reducer to update the store, setting an active category.

## tasks

- [x] Create a new component `<categories />`
- [x] Interface with Redux store to get available categories
- [x] On selection, fire off a reducer to change active category
