### ISSUE TITLE
Modularize and refactor state logic

### ISSUE THREAD

**Issue by CullenSharp** [CullenSharp/redux-store#11]
## Overview

`Categories.js` is becoming verbose and monolithic. I want to extract it's bits and pieces into modules on reducer/action. Hopefully this will make the code base easier to follow and maintain.

## Tasks

- [x] Split `Catagories.js` in three by reducer: `categories`, `cart`, and `products`
- [x] Convert all complex datatypes to classes (refer to #14 for model)
- [x] Move actions to their own modules
- [x] Import and combine reducers at `index.js`

**Comment by CullenSharp** [comment]
- [ ] Convert all complex datatypes to classes: category/product (refer to #14 for model)
