### ISSUE TITLE
Track inventory on product

### ISSUE THREAD

**Issue by CullenSharp** [CullenSharp/redux-store#12]
## Overview

Change the model in store to track the __# in inventory__ on each product. Make it respond to changes at the component level. Refer to issue #11 before working on this.

## Tasks
- [x] Remove the input on `<SimpleCart />` 
- [x] #14
- [x] Increment cart size when item added
- [x] Decrement __inventory__ on add
- [x] Increment __inventory__ on remove
- [x] #13
