### ISSUE TITLE
Fetch categories

### ISSUE THREAD

**Issue by CullenSharp** [CullenSharp/redux-store#16]
## Overview

I want to load categories from an api on start.

## Tasks
- [x] Install Axios
- [x] Install Redux Thunk
- [x] Write async action
- [x] Add case on categories reducer
- [x] Fetch categories when `<Categories />` mounts
