### ISSUE TITLE
Fetch products

### ISSUE THREAD

**Issue by CullenSharp** [CullenSharp/redux-store#17]
## Overview

I want to load products from an api on start.

## Tasks
- [x] Install Axios
- [x] Install Redux Thunk
- [x] Write async action
- [x] Fetch products when `<Products />` mounts
