### ISSUE TITLE
Filter products by category

### ISSUE THREAD

**Issue by CullenSharp** [CullenSharp/redux-store#2]
## As a user, I want to choose a category and see a list of all available products matching that category

Sort products by active category and render them to the page.

## Tasks

- [x] Create a `<products />` component
- [x] Interface with Redux store to get available products
- [x] Sort by active category
- [x] Render the product list to the view
