### ISSUE TITLE
Add checkout page

### ISSUE THREAD

**Issue by CullenSharp** [CullenSharp/redux-store#20]
# As a user, I want to be able to go to a checkout page.

## Overview

Add a `<Checkout />` component that renders a payment info form, subtotal, and a list of items in the cart.

## Tasks

- [x] Add a new component called `<Checkout />`
- [x] Render at route 'checkout'
- [x] Display a list of products in cart
- [ ] Add up the total of all items prices
- [ ] Render a form for entering payment info
