### ISSUE TITLE
Add product details page

### ISSUE THREAD

**Issue by CullenSharp** [CullenSharp/redux-store#21]
# As a user, I want to view detailed information about a product

## Overview

Add a new component `<ProductDetails />` that renders product info, product suggestions, and an add to cart button.

## Tasks

- [x] Create a new component in the Product component folder
- [x] Get a reference to the clicked on product and render it
- [x] Pipe in actions (ADD_ITEM_TO_CART) and dispatch
- [x] Render at route /products/:id

## Example

```JS
  <Switch>
      <Route path="/:id" children={<Child />} />
  </Switch>
```

[(source)](https://reactrouter.com/web/example/url-params)

Note: you can refer to `/:id` with useParams hook from react-router-dom
