### ISSUE TITLE
Style the view layer

### ISSUE THREAD

**Issue by CullenSharp** [CullenSharp/redux-store#3]
## As a user, I want a clean, easy to use user interface so that I can shop the online store with confidence

Style the view layer so that it is intuitive and convenient for the user.

## Tasks

- [x] Install Material UI
- [ ] Style using Material component kit
- [ ] Avoid inline styles

## Preview

![Preview of final view](https://github.com/codefellows/seattle-code-javascript-401d42/raw/main/class-36/lab/preview.png)
