### ISSUE TITLE
Create <SimpleCart /> component

### ISSUE THREAD

**Issue by CullenSharp** [CullenSharp/redux-store#5]
# As a user, I want to see the products that I’ve added to my shopping cart so that

## Overview

Create a new component `<SimpleCart />` to render items from the Redux store. 

## Tasks

- [x] Create a Cart component
- [x] Interface with Redux store
- [x] Store reference to cart items in a stateful variable __products__
- [x] Render stored items

**Comment by CullenSharp** [comment]
This feature is reliant on #6 as we need to add items to a cart before rendering.
