### ISSUE TITLE
Add item to cart

### ISSUE THREAD

**Issue by CullenSharp** [CullenSharp/redux-store#6]
# As a user, I want to choose from products in the list and add them to my shopping cart

## Overview

Create a property on store to track items in a cart, then create a function to manage manipulations to that property.

## Tasks

- [x] Add cart as a property to the store
- [x] Create an action creator for adding items
- [x] Add a case to our reducer to manage a cart
- [x] Hook action up to `<Product />`
