### ISSUE TITLE
Increment/decrement quantity of items in cart

### ISSUE THREAD

**Issue by CullenSharp** [CullenSharp/redux-store#7]
# As a user, I want to change the quantity of items I intend to purchase in my shopping cart

## Overview

Write a function to increment/decrement the quantity of an item in the cart.

## Tasks

- [x] Track item quantity in Redux Store
- [x] Add action creator to update quantity
- [x] Add reducer to increment/decrement quantity
- [x] Add numeric input
- [x] Watch for changes to render increment/decrement __quantity__
