### ISSUE TITLE
Remove item from <SimpleCart />

### ISSUE THREAD

**Issue by CullenSharp** [CullenSharp/redux-store#8]
# As a user, I want to be able to remove an item from my shopping cart

## Overview

Add the functionality to remove items from a users cart.

## Tasks

- [x] Add action creator for removing items from cart
- [x] Update cases on reducer to remove items from cart
- [x] Utilize useEffect hook to update __products__ when cart changes
- [x] Re-render products without removed item
