### ISSUE TITLE
Create <ActiveCategory /> component

### ISSUE THREAD

**Issue by CullenSharp** [CullenSharp/redux-store#9]
# As a user, I want to see the name of the category I'm currently viewing

## Overview

Build a component that renders the active category to the view. Refer to issue #3 for reference. 

## Tasks

- [x] Create new component `<ActiveCategory />`
- [x] Add stateful value to track activeCategory
- [x] Interface with Redux store
- [x] Utilize useEffect to update the activeCategory as it changes
